### ISSUE TITLE
Failure registering the Service Worker

### ISSUE THREAD

**Issue by md4r2** [holy-unblocker/website-aio#4] opened 2022-09-12 21:55 UTC
When loading any page, these errors come up:
Failure registering the Ultraviolet/Stomp Service Worker;
Unable to create a new Rammerhead session.

Pages are completely failing to load.

I am using [https://website-aio-e9x.koyeb.app/](https://website-aio-e9x.koyeb.app/)

**Comment by e9x** [comment] 2022-09-13 00:50
I will investigate this issue. In the meantime, can you try the Heroku deployment?
https://website-aio.herokuapp.com/
My theory right now is the Koyeb instance is running out of resources (we only allocated it 256 MB)
Maybe you can deploy it yourself and see if you still run into the same issue.

**Comment by md4r2** [comment] 2022-09-13 12:32
Hi
I've tried deploying to heroku and rammerhead seems to be mostly working fine when i tested with yt but ultraviolet & stomp have the same issue as the koyeb instance.
As for replit, when running it comes up with the error:
sh: line 1: cross-env: command not found
exit status 127

Ultraviolet on [https://website-aio.herokuapp.com/](https://website-aio.herokuapp.com/) seems to be working fine with yt, rammerhead is partially working (can't play vids from yt unless direct/embed link is entered) and stomp has the same issue.

Hope this helps :D

**Comment by e9x** [comment] 2022-09-14 02:54
Fixed in upstream website repository.
See https://git.holy.how/holy/website/commit/1069565562ac96d9ad20936fd5d4ac97ac438490
This repository is now updated and works as intended.

**Closed by e9x** 2022-09-14 02:54 UTC
